# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e35b301b0ba2222405ece07ce6cfb86f383f6a34a0183453332d7d602f6d09408e0e29a6192c9815a52a218865166d63f6d08de1ce14a1d2a5dc6e28bcbea33

test:
  secret_key_base: bef8b2516b9034c6923885f715e8164339ea117eb33b667f6e8c4a323b854798b2bbe57f266ed2de94cf92b8f2f53fe6ac73e8516e47f0a3a7d2cbfb5c6bedb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
